import { useState, useRef, useEffect, type ReactNode } from "react";
import { AlertTriangle, CheckCircle, XCircle, ExternalLink, Download, FileText, FileDown, Activity, Heart, Shield, ShieldAlert, ChevronDown } from "lucide-react";
import { useAppStore } from "../../store/useAppStore";
import type { AppropriatenessRating, AppropriatenessResult, ImagingOrder, PatientProfile } from "../../types";
import { formatDate } from "../../utils/constants";
import { sanitizeFilename } from "../../utils/sanitize";
import { downloadBlob } from "../../utils/download";
import { exportAppropriatenessPDF } from "../../utils/pdfExport";
import { useToast } from "../common/Toast";

const verdictConfig: Record<
  AppropriatenessRating,
  { label: string; bannerClass: string; icon: ReactNode }
> = {
  USUALLY_APPROPRIATE: {
    label: "Usually Appropriate",
    bannerClass: "bg-green-50 border-green-300 text-green-800",
    icon: <CheckCircle className="w-6 h-6 text-green-600" />,
  },
  MAY_BE_APPROPRIATE: {
    label: "May Be Appropriate",
    bannerClass: "bg-amber-50 border-amber-300 text-amber-800",
    icon: <AlertTriangle className="w-6 h-6 text-amber-600" />,
  },
  USUALLY_NOT_APPROPRIATE: {
    label: "Usually Not Appropriate",
    bannerClass: "bg-red-50 border-red-300 text-red-800",
    icon: <XCircle className="w-6 h-6 text-red-600" />,
  },
};

const severityBadgeClass: Record<string, string> = {
  HIGH: "bg-red-100 text-red-800 border border-red-200",
  MEDIUM: "bg-amber-100 text-amber-800 border border-amber-200",
  LOW: "bg-gray-100 text-gray-700 border border-gray-200",
};

/** Export appropriateness assessment as CSV */
function exportAppropriatenessCSV(
  result: AppropriatenessResult,
  order: ImagingOrder,
  patient: PatientProfile
) {
  const lines: string[] = [];

  // Summary section
  lines.push("APPROPRIATENESS ASSESSMENT REPORT");
  lines.push(`"Patient","${patient.name}"`);
  lines.push(`"MRN","${patient.mrn}"`);
  lines.push(`"DOB","${patient.dob}"`);
  lines.push(`"Date Generated","${new Date().toISOString().split("T")[0]}"`);
  lines.push("");
  lines.push(`"Order Under Review","${order.studyDescription}"`);
  lines.push(`"Clinical Indication","${order.clinicalIndication}"`);
  lines.push(`"Overall Verdict","${verdictConfig[result.overallVerdict].label}"`);
  lines.push(`"Summary","${result.summary}"`);
  lines.push(`"Prior Scan Summary","${result.priorScanSummary}"`);
  lines.push("");

  // Alert details
  lines.push("ALERTS");
  lines.push('"Rule ID","Title","Severity","Rating","Description","Recommendation","Citation"');
  for (const alert of result.alerts) {
    lines.push(
      [
        alert.ruleId,
        alert.title,
        alert.severity,
        alert.rating,
        alert.description,
        alert.recommendation,
        alert.citation,
      ]
        .map((cell) => `"${String(cell).replace(/"/g, '""')}"`)
        .join(",")
    );
  }

  downloadBlob(
    lines.join("\n"),
    `appropriateness-${sanitizeFilename(patient.name)}.csv`,
    "text/csv;charset=utf-8;"
  );
}

/** Export appropriateness assessment as a plain-text report */
function exportAppropriatenessText(
  result: AppropriatenessResult,
  order: ImagingOrder,
  patient: PatientProfile
) {
  const lines: string[] = [];
  const sep = "─".repeat(60);

  lines.push("RADVIEW — APPROPRIATENESS ASSESSMENT REPORT");
  lines.push(sep);
  lines.push(`Patient:    ${patient.name}`);
  lines.push(`MRN:        ${patient.mrn}`);
  lines.push(`DOB:        ${formatDate(patient.dob)}`);
  lines.push(`Generated:  ${formatDate(new Date().toISOString().split("T")[0])}`);
  lines.push("");
  lines.push(`ORDER UNDER REVIEW`);
  lines.push(`  Study:       ${order.studyDescription}`);
  lines.push(`  Indication:  ${order.clinicalIndication}`);
  lines.push(`  Physician:   ${order.orderingPhysician}`);
  lines.push(`  Urgency:     ${order.urgency}`);
  lines.push("");
  lines.push(sep);
  lines.push(`OVERALL VERDICT: ${verdictConfig[result.overallVerdict].label.toUpperCase()}`);
  lines.push(`Summary: ${result.summary}`);
  lines.push(`Prior Scans: ${result.priorScanSummary}`);
  lines.push(sep);
  lines.push("");
  lines.push(`ALERTS (${result.alerts.length})`);

  for (const alert of result.alerts) {
    lines.push("");
    lines.push(`  [${alert.severity}] ${alert.title}`);
    lines.push(`  ${alert.description}`);
    lines.push(`  Recommendation: ${alert.recommendation}`);
    lines.push(`  Citation: ${alert.citation}`);
    if (alert.citationUrl) {
      lines.push(`  Link: ${alert.citationUrl}`);
    }
  }

  lines.push("");
  lines.push(sep);
  lines.push("This report was generated by RadView for decision-support purposes only.");
  lines.push("It does not constitute medical advice. Clinical judgment should always prevail.");

  downloadBlob(
    lines.join("\n"),
    `appropriateness-report-${sanitizeFilename(patient.name)}.txt`,
    "text/plain;charset=utf-8;"
  );
}

/** Unified export dropdown replacing three separate buttons */
const ExportDropdown = ({
  result,
  order,
  patient,
  showToast,
}: {
  result: AppropriatenessResult;
  order: ImagingOrder;
  patient: PatientProfile;
  showToast: (msg: string) => void;
}) => {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  const items = [
    {
      label: "PDF Report",
      icon: <FileDown className="w-3.5 h-3.5" />,
      action: () => { exportAppropriatenessPDF(result, order, patient); showToast("PDF downloaded!"); },
    },
    {
      label: "Text Report",
      icon: <FileText className="w-3.5 h-3.5" />,
      action: () => { exportAppropriatenessText(result, order, patient); showToast("Report downloaded!"); },
    },
    {
      label: "CSV Data",
      icon: <Download className="w-3.5 h-3.5" />,
      action: () => { exportAppropriatenessCSV(result, order, patient); showToast("CSV downloaded!"); },
    },
  ];

  return (
    <div className="relative" ref={ref}>
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 text-sm text-gray-600 hover:text-gray-900 px-3 py-1.5 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
        aria-expanded={open}
        aria-label="Export report"
      >
        <Download className="w-4 h-4" />
        Export
        <ChevronDown className={`w-3.5 h-3.5 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-1 w-44 bg-white rounded-lg shadow-lg border border-gray-200 z-50 py-1">
          {items.map((item) => (
            <button
              key={item.label}
              onClick={() => { item.action(); setOpen(false); }}
              className="w-full flex items-center gap-2.5 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50 transition-colors text-left"
            >
              {item.icon}
              {item.label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

export const AppropriatenessView = () => {
  const analysisResult = useAppStore((s) => s.analysisResult);
  const order = useAppStore((s) => s.order);
  const patient = useAppStore((s) => s.patient);
  const result = analysisResult?.appropriateness;
  const { show: showToast, ToastElement } = useToast();

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-lg font-semibold text-gray-900 mb-1">
            Appropriateness Analysis
          </h2>
          <p className="text-sm text-gray-500">
            Evidence-based assessment of the current imaging order.
          </p>
        </div>
        {result && (
          <ExportDropdown result={result} order={order} patient={patient} showToast={showToast} />
        )}
        {ToastElement}
      </div>

      {/* Current Order + Clinical Context */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div className="bg-white border border-gray-200 rounded-lg p-4">
          <h3 className="text-xs font-medium text-gray-500 uppercase mb-2">
            Current Order Under Review
          </h3>
          <p className="font-medium text-gray-900">{order.studyDescription}</p>
          <p className="text-sm text-gray-600 mt-1">
            Indication: {order.clinicalIndication}
          </p>
          <div className="flex flex-wrap gap-2 mt-3 text-xs text-gray-500">
            <span className="px-2 py-0.5 bg-gray-50 rounded">Physician: {order.orderingPhysician}</span>
            <span className="px-2 py-0.5 bg-gray-50 rounded">Urgency: {order.urgency}</span>
            <span className="px-2 py-0.5 bg-gray-50 rounded">Contrast: {order.contrast.replace(/_/g, " ")}</span>
          </div>
        </div>

        <div className="bg-slate-50 border border-slate-200 rounded-lg p-4">
          <h3 className="text-xs font-medium text-slate-500 uppercase mb-2 flex items-center gap-1.5">
            <Shield className="w-3.5 h-3.5" />
            Clinical Safety Context
          </h3>
          <div className="space-y-2 text-sm">
            <div className="flex items-center gap-2">
              <Heart className="w-3.5 h-3.5 text-rose-400 flex-shrink-0" />
              <span className="text-gray-700">
                {patient.conditions.length > 0
                  ? patient.conditions.join(", ")
                  : "No documented conditions"}
              </span>
            </div>
            <div className="flex items-center gap-2">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-400 flex-shrink-0" />
              <span className="text-gray-700">
                {patient.allergies.length > 0
                  ? `Allergies: ${patient.allergies.join(", ")}`
                  : "No known drug allergies (NKDA)"}
              </span>
            </div>
            {patient.renalFunction && (
              <div className="flex items-center gap-2">
                <Activity className={`w-3.5 h-3.5 flex-shrink-0 ${
                  patient.renalFunction.eGFR < 30 ? "text-red-500" :
                  patient.renalFunction.eGFR < 60 ? "text-amber-500" :
                  "text-blue-400"
                }`} />
                <span className={`${
                  patient.renalFunction.eGFR < 60 ? "text-amber-700 font-medium" : "text-gray-700"
                }`}>
                  eGFR {patient.renalFunction.eGFR} mL/min · Cr {patient.renalFunction.creatinine} mg/dL
                  {patient.renalFunction.eGFR < 30 && " — Severe impairment"}
                  {patient.renalFunction.eGFR >= 30 && patient.renalFunction.eGFR < 60 && " — Moderate impairment"}
                </span>
              </div>
            )}
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-500">
                {patient.age}{patient.gender?.[0]} · Pregnancy: {patient.pregnancyStatus?.replace(/_/g, " ") ?? "N/A"}
              </span>
            </div>
          </div>
        </div>
      </div>

      {!result ? (
        <div className="bg-gradient-to-br from-slate-50 to-blue-50 border border-slate-200 rounded-xl p-10 text-center">
          <div className="w-14 h-14 bg-blue-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <ShieldAlert className="w-7 h-7 text-blue-500" />
          </div>
          <p className="text-base font-medium text-slate-700 mb-1">No analysis results yet</p>
          <p className="text-sm text-slate-500 max-w-md mx-auto">
            Click <span className="font-semibold text-blue-600">Run Analysis</span> above to evaluate
            the current imaging order against 18 evidence-based appropriateness rules.
          </p>
          <div className="mt-5 flex flex-wrap justify-center gap-2 text-[11px] text-slate-400">
            <span className="px-2 py-1 bg-white rounded-full border border-slate-200">ACR Criteria</span>
            <span className="px-2 py-1 bg-white rounded-full border border-slate-200">Choosing Wisely</span>
            <span className="px-2 py-1 bg-white rounded-full border border-slate-200">Fleischner</span>
            <span className="px-2 py-1 bg-white rounded-full border border-slate-200">Lung-RADS</span>
            <span className="px-2 py-1 bg-white rounded-full border border-slate-200">BI-RADS</span>
          </div>
        </div>
      ) : (
        <>
          {/* Verdict Banner */}
          <div
            className={`border rounded-lg p-6 text-center ${
              verdictConfig[result.overallVerdict].bannerClass
            }`}
          >
            <div className="flex items-center justify-center gap-3">
              {verdictConfig[result.overallVerdict].icon}
              <span className="text-xl font-bold">
                {verdictConfig[result.overallVerdict].label}
              </span>
            </div>
            <p className="mt-2 text-sm">
              {result.alerts.length} alert{result.alerts.length !== 1 && "s"}{" "}
              identified · {result.summary}
            </p>
            {result.priorScanSummary && (
              <p className="mt-1 text-xs opacity-75">
                Prior imaging: {result.priorScanSummary}
              </p>
            )}
            <p className="mt-1 text-xs opacity-60">
              Evaluated against 18 deterministic rules (ACR · Choosing Wisely · Fleischner · Lung-RADS · BI-RADS).
              Always correlate with full clinical context.
            </p>
          </div>

          {/* Alert Cards */}
          <div className="space-y-4">
            {result.alerts.map((alert) => (
              <div
                key={alert.ruleId}
                className="bg-white border border-gray-200 rounded-lg p-4"
              >
                <div className="flex items-start justify-between mb-2">
                  <h4 className="font-medium text-gray-900">{alert.title}</h4>
                  <span
                    className={`px-2 py-1 rounded text-xs font-medium flex-shrink-0 ml-2 ${
                      severityBadgeClass[alert.severity] ?? severityBadgeClass.LOW
                    }`}
                  >
                    {alert.severity}
                  </span>
                </div>
                <p className="text-sm text-gray-600">{alert.description}</p>
                <p className="text-sm text-gray-800 mt-2 font-medium">
                  {alert.recommendation}
                </p>
                {alert.citationUrl ? (
                  <a
                    href={alert.citationUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-blue-500 hover:text-blue-700 mt-2 inline-flex items-center gap-1"
                  >
                    {alert.citation}
                    <ExternalLink className="w-3 h-3" />
                  </a>
                ) : (
                  <p className="text-xs text-gray-500 mt-2">{alert.citation}</p>
                )}
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
};
